### ISSUE TITLE
Problems to login to SONATA Service platform

### ISSUE THREAD

**Issue by tigarto** [sonata-nfv/son-install#159] opened 2018-03-22 21:18 UTC
Hi, 
When I installed the sonata platform (v 3,0) (previously i had edited the Sonata SP user in ```roles/sp/defaults/main.yml```). Initially, I could login and exit normally, but after installing the son-cli and son-emu in the PC. I couldn't login again to SONATA SP.

What can I do?

Best regards

**Comment by arocha7** [comment] 2018-03-23 09:46
Hello, 1st it's nice to hear your interest on 'son-install'. I've tried to reproduce the reported issue at our premises but did not face similar behavior. Here is my steps:
1. get 'son-install' repo
2. run 'son-cmud' in dry mode with settings for both scenarios:
* Openstack VIM
$ ansible-playbook son-cmud.yml -e "ops=create plat=sp pop=ncsrd proj=dem distro=xenial" -v --check
* localhost
$ ansible-playbook utils/deploy/sp.yml -e target=localhost -v --check
3. get 'son-cli' repo
4. re-run 'son-install'

So, let me hear some more details about your deployment, namely: 
a) what is the deployment scenario? [localhost/openstack]
b) did you create the hidden vault password for 'sonata' as requested in 'ansible.cfg'?
vault_password_file = ~/.ssh/.vault_pass

**Comment by tigarto** [comment] 2018-03-23 16:47
Hi arocha7,

Thanks for the quick reply. I think so that sonata is an excellent platform, therefore I am trying to install it in my laptop and I want to test the tool ASAP. For achieving that I follow the next steps:
1. In the son-install directory I run the command to localhost (development scenario):

```
ansible-playbook utils/deploy/sp.yml -e target=localhost -v --check
```
About the questions these are the answers:
a. deployment scenario: localhost
b. Yes.

Now, when I run the command, I have the next output:

```
... # Previus output
... # Previus output

TASK [sp : debug] ************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "##### SP GUI DEPLOYMENT 20180323-1145"
}

TASK [sp : GATEKEEPER GUI - running Docker containers] ***********************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: __init__() got an unexpected keyword argument 'auto_remove'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_NpeRsx/ansible_module_docker_container.py\", line 2124, in <module>\n    main()\n  File \"/tmp/ansible_NpeRsx/ansible_module_docker_container.py\", line 2119, in main\n    cm = ContainerManager(client)\n  File \"/tmp/ansible_NpeRsx/ansible_module_docker_container.py\", line 1759, in __init__\n    self.present(state)\n  File \"/tmp/ansible_NpeRsx/ansible_module_docker_container.py\", line 1797, in present\n    new_container = self.container_create(self.parameters.image, self.parameters.create_parameters)\n  File \"/tmp/ansible_NpeRsx/ansible_module_docker_container.py\", line 891, in create_parameters\n    host_config=self._host_config(),\n  File \"/tmp/ansible_NpeRsx/ansible_module_docker_container.py\", line 989, in _host_config\n    return self.client.create_host_config(**params)\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/container.py\", line 587, in create_host_config\n    return HostConfig(*args, **kwargs)\nTypeError: __init__() got an unexpected keyword argument 'auto_remove'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/home/tigarto/son-install/utils/deploy/sp.retry

PLAY RECAP *******************************************************************************************************************************************************
localhost                  : ok=44   changed=7    unreachable=0    failed=1   
```
I attach the log:

[ansible.log](https://github.com/sonata-nfv/son-install/files/1842598/ansible.log)

Best regards.

**Comment by arocha7** [comment] 2018-03-26 14:21
It seems that you have run it with "--check". That is only used to verify the playbook sintax and step by step execution but without creating resources.  You should run it in normal mode:

$ ansible-playbook utils/deploy/sp.yml -e target=localhost -v

Also make sure you have more that 4GB RAM at your laptop. In the end you'll get two web applications: 
* the SP: http://<your-local-ip-addr>
* the BSS: http://<your-local-ip-addr>:25001

Looking forward to hear from you.

**Comment by tigarto** [comment] 2018-03-27 02:15
Hi, thack you again for the help.
1. My laptop has 8GB RAM.
2. I running the command:

```
$ sudo ansible-playbook utils/deploy/sp.yml -e target=localhost -v
``` 
But, now the error is the following:

```
TASK [sp : MONIT InfluxDB  - running Docker containers] ******************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pulling image sonatanfv/son-monitor-influxdb:dev - 'module' object has no attribute 'get_config_header'"}
	to retry, use: --limit @/home/tigarto/son-install/utils/deploy/sp.retry

PLAY RECAP ***************************************************************************************************************************
localhost                  : ok=44   changed=7    unreachable=0    failed=1   
```
I search in the web and I found in [the next link](https://github.com/docker/compose/issues/4385) a possible answer? I installed a docker-compose but the error persist. Do you think it's a good idea to reinstall the docker related tools?

Looking forward to hear from you.

**Comment by arocha7** [comment] 2018-03-28 10:28
Hi, before run the 'sp.yml' playbook to deploy the SONATA SP platform, my suggestion is to previously run a similar playbook to deploy the Docker engine:

$ ansible-playbook utils/deploy/docker.yml -e "target=localhost plat=docker" -vvvv

$ ansible-playbook utils/deploy/sp.yml -e "target=localhost plat=sp" -vvvv

Also use 4 'v' in the CLI to get higher verbosity.

then let me know how it is. Regards

**Comment by tigarto** [comment] 2018-03-29 17:40
Hi, 
Thank you again. I follow the instructions. These are the results:
1. **Command 1**:

```sudo ansible-playbook utils/deploy/docker.yml -e "target=localhost plat=docker" -vvvv```

**Output 1**: There were no mistakes. I attach the results in the next log: 
[output1_deploy_docker.log](https://github.com/sonata-nfv/son-install/files/1861251/output1_deploy_docker.log)

2. **Command 2**:

```sudo ansible-playbook utils/deploy/sp.yml -e "target=localhost plat=sp" -vvvv```

**Output 2**: There were mistakes. In the next log 
[output2_deploy_sp.log](https://github.com/sonata-nfv/son-install/files/1861263/output2_deploy_sp.log) is the output.

Looking forward to hear from you.

Best regards.

**Comment by arocha7** [comment] 2018-04-02 14:48
Hi, i don't explanation for this error unless for the fact this is invoking a 4 months old image tagged 'dev'. As a workaroung, my suggestion is:

a) overload the "sp_ver" parameter in the command line, like:
```
$ ansible-playbook utils/deploy/sp.yml -e "plat=sp pop=alabs proj=dem distro=xenial" -v --limit @/home/ubuntu/son-install-SON-MST/utils/deploy/sp.retry
```

b) change 'sp_ver' in the Role's defaults file to "latest"
```
$ vi roles/sp/defaults/main.yml
sp_ver: latest
```

**Comment by felipevicens** [comment] 2018-04-02 15:01
Hello @tigarto seems your PC can't download the image ***sonatanfv/son-monitor-influxdb***
`msg": "Error pulling image sonatanfv/son-monitor-influxdb:dev`
As you can see in dockerhub, the image is available.

[docker hub](https://hub.docker.com/r/sonatanfv/son-monitor-influxdb/tags/)

Can you try to pull it directly from your linux console?

```
docker pull sonatanfv/son-monitor-influxdb:dev
```

**Comment by tigarto** [comment] 2018-04-05 01:25
Hi @arocha7 and @felipevicens. Follow the instructions of @felipevicens, i check and i found a problem in that my docker image was sonatanfv/son-monitor-influxdb:3.0. Then, I removed this image and run the command 
```
docker pull sonatanfv/son-monitor-influxdb:dev
```
Now, I have the image: son-monitor-influxdb:dev.

Next, I don't change the **sp_ver** to **latest** beacuse the pull problem is no longer. But now, when i run the command:

```
sudo ansible-playbook utils/deploy/sp.yml -e "target=localhost plat=sp" -vvv 
``` 
A new error is showed. Here is the log:
[output.log](https://github.com/sonata-nfv/son-install/files/1878303/output.log)

Looking forward to hear from you.

Best regards.

**Comment by tigarto** [comment] 2018-04-05 02:34
Hi @arocha7 and @felipevicens, the install was completed, i unistall docker-py (v 1.9.0) and install docker-py (v 1.10.0) using pip. 
Why in sonata de version to docker-py is 1.9.0 (https://github.com/sonata-nfv/son-install/search?utf8=%E2%9C%93&q=docker-py&type=)

Is necessary change this in the config files of sonata install from beggining?

Thanks again,

Looking forward to hear from you.

Best regards.

**Comment by arocha7** [comment] 2018-04-05 10:14
Hi, in fact "docker-py=1.9.0" was a wrong fix that comes from 'Ubuntu 14.04' support due to the usage of docker-compose 1.8.0 at that time. In the next couple of days it will be removed on the upstream release. 
Now you are ready to connect your SP to an Openstack VIM (actually the only supported VIM). If this is the case, let us know your evolution steps.
All the best

**Comment by tigarto** [comment] 2018-04-06 14:03
Hi, 
Thank you very much to all. Your help was very valuable. The next step is start with the tutorials. I hope enjoy it.

All the best.

**Comment by felipevicens** [comment] 2018-04-10 19:16
Thanks @tigarto for your feedback. I'm closing this issue since your issue was fixed.

**Closed by felipevicens** 2018-04-10 19:16 UTC
